# Generated by Django 5.0 on 2023-12-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='appuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
