# Generated by Django 5.0 on 2023-12-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_reservation', '0002_remove_appuser_user_id_appuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
