# Generated by Django 5.0 on 2023-12-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_reservation', '0003_alter_appuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='id',
            new_name='user_id',
        ),
    ]
